# Generated by Django 4.1.2 on 2022-11-08 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('keyword', models.CharField(blank=True, max_length=40, null=True, verbose_name='Keywords')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UpdatedDate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Diary',
            },
        ),
    ]
