# Generated by Django 4.1.2 on 2022-11-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Document'},
        ),
    ]
